
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emznmqeenclngbntgauy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtem5tcWVlbmNsbmdibnRnYXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDUxMzIsImV4cCI6MjA1OTgyMTEzMn0.JslC26InwVlm-GcbgQtEaaKP6EkWMizh1U4ISDgo0wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
